[workspace]
members = [
    'node',
    'runtime',
    'precompiles/utils',
    'precompiles/utils/macro',

]

[patch.crates-io]
jsonrpsee = { git = "https://github.com/peaqnetwork/jsonrpsee", branch = "peaq-v0.15.1" }
jsonrpsee-core = { git = "https://github.com/peaqnetwork/jsonrpsee", branch = "peaq-v0.15.1" }
jsonrpsee-types = { git = "https://github.com/peaqnetwork/jsonrpsee", branch = "peaq-v0.15.1" }

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
codegen-units = 1
incremental = false
inherits = "release"
lto = true

[profile.release]
# Peaq runtime requires unwinding.
opt-level = 3
panic = "unwind"
