[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
]

[patch.crates-io]
ethereum = { git = "https://github.com/purestake/ethereum", branch = "tgm-0.11.1-typeinfo-patch" }
