[workspace]
members = [
    'node',
    'pallets/*',
    'runtime/*',
    'primitives/xcm',
    'precompiles/utils',
    'precompiles/utils/macro',
]

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
codegen-units = 1
incremental = false
inherits = "release"
lto = true

[profile.release]
# Peaq runtime requires unwinding.
opt-level = 3
panic = "unwind"
