[package]
name = "peaq-rpc-core-txpool"
license = "GPL-3.0-only"
version = "0.6.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
ethereum-types = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = ["derive"] }
serde_json = { workspace = true, default-features = true }

ethereum = { workspace = true, default-features = true, features = [ "with-codec" ] }
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }

fc-rpc-core = { workspace = true, default-features = true }
