[package]
name = "peaq-rpc-core-trace"
license = "GPL-3.0-only"
version = "0.6.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
ethereum-types = { workspace = true, default-features = true }
futures = { workspace = true, default-features = true, features = ["compat"] }
jsonrpsee = { workspace = true, default-features = false, features = ["macros", "server"] }
peaq-client-evm-tracing = { workspace = true }
peaq-rpc-core-types = { workspace = true }
serde = { workspace = true, default-features = true, features = ["derive"] }
serde_json = { workspace = true, default-features = true }
