[package]
name = "peaq-rpc-core-trace"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
ethereum-types = "0.14.1"
futures = { version = "0.3.1", features = [ "compat" ] }
jsonrpsee = { version = "0.16.2", default-features = false, features = [ "macros", "server" ] }
peaq-client-evm-tracing = { path = "../../evm-tracing" }
peaq-rpc-core-types = { path = "../types" }
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0"
