[package]
name = "peaq-rpc-core-trace"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
ethereum-types = { workspace = true, default-features = true }
futures = { version = "0.3.1", features = [ "compat" ] }
jsonrpsee = { git = "https://github.com/peaqnetwork/jsonrpsee", branch = "peaq-v0.15.1", default-features = false, features = [ "macros", "server" ] }
peaq-client-evm-tracing = { path = "../../evm-tracing" }
peaq-rpc-core-types = { path = "../types" }
serde = { workspace = true, features = [ "derive" ] }
serde_json = "1.0"
