[package]
name = "peaq-rpc-primitives-debug"
authors = [ "peaq network <https://github.com/peaqnetwork>" ]
edition = "2021"
homepage = "https://peaq.network/"
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.1.0"

[dependencies]
environmental = { version = "1.1.2", default-features = false }
ethereum = { workspace = true, features = [ "with-codec" ] }
ethereum-types = { workspace = true }
hex = { version = "0.4", optional = true, features = [ "serde" ] }
serde = { workspace = true, optional = true, features = [ "derive" ] }
serde_json = { version = "1.0", optional = true }

# Substrate
codec = { workspace = true }
sp-api = { git = "https://github.com/peaqnetwork/substrate.git", branch = "peaq-polkadot-v0.9.38", default-features = false }
sp-core = { workspace = true }
sp-io = { git = "https://github.com/peaqnetwork/substrate.git", branch = "peaq-polkadot-v0.9.38", default-features = false }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"environmental/std",
	"ethereum-types/std",
	"ethereum/std",
	"hex",
	"serde",
	"serde_json",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
