[package]
name = 'peaq-krest-runtime'
version = '3.0.0-polkadot-v0.9.38'
description = 'A node of the peaq network.'
authors = ['peaq network <https://github.com/peaqnetwork>']
homepage = 'https://peaq.network/'
edition = '2021'
license = 'Unlicense'
publish = false
repository = 'https://github.com/peaqnetwork/peaq-network-node/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies.substrate-wasm-builder]
git = 'https://github.com/peaqnetwork/substrate'
branch = 'peaq-polkadot-v0.9.38'

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
smallvec = { workspace = true }
rlp = { workspace = true, optional = true  }
sha3 = { workspace = true, optional = true  }
frame-benchmarking = { workspace = true, optional = true  }
frame-executive = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
hex-literal = { workspace = true, optional = true  }
pallet-aura = { workspace = true }
pallet-balances = { workspace = true }
pallet-randomness-collective-flip = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
scale-info = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
pallet-contracts = { workspace = true }
pallet-contracts-primitives = { workspace = true }
peaq-pallet-did = { workspace = true }
peaq-pallet-did-runtime-api = { workspace = true }
peaq-pallet-transaction = { workspace = true }
peaq-pallet-rbac = { workspace = true }
peaq-pallet-rbac-runtime-api = { workspace = true }
peaq-pallet-storage = { workspace = true }
peaq-pallet-storage-runtime-api = { workspace = true }
pallet-multisig = { workspace = true }
pallet-utility = { workspace = true }
pallet-treasury = { workspace = true }
pallet-vesting = { workspace = true }
sp-io = { workspace = true }
fp-evm = { workspace = true }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true }
pallet-base-fee = { workspace = true }
pallet-dynamic-fee = { workspace = true }
pallet-ethereum = { workspace = true }
pallet-evm = { workspace = true }
pallet-evm-precompile-blake2 = { workspace = true }
pallet-evm-precompile-bn128 = { workspace = true }
pallet-evm-precompile-dispatch = { workspace = true }
pallet-evm-precompile-modexp = { workspace = true }
pallet-evm-precompile-sha3fips = { workspace = true }
pallet-evm-precompile-simple = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-aura-ext = { workspace = true }
parachain-info = { workspace = true }
polkadot-parachain = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-runtime-common = { workspace = true }
pallet-session = { workspace = true }
pallet-authorship = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
pallet-xcm = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
orml-currencies = { workspace = true }
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
orml-xtokens = { workspace = true }
orml-unknown-tokens = { workspace = true }
orml-xcm-support = { workspace = true }
pallet-collective = { workspace = true }
sp-weights = { workspace = true }

evm-tracing-events = { path = '../../primitives/rpc/evm-tracing-events', optional = true, default-features = false }
peaq-evm-tracer = { path = '../evm_tracer', optional = true, default-features = false }
peaq-rpc-primitives-debug = { path = '../../primitives/rpc/debug', default-features = false }
peaq-rpc-primitives-txpool = { path = '../../primitives/rpc/txpool', default-features = false }

frame-support = { workspace = true }

parachain-staking = { path = '../../pallets/parachain-staking', default-features = false }
pallet-block-reward = { path = '../../pallets/block-reward', default-features = false }
peaq-primitives-xcm = { path = '../../primitives/xcm', default-features = false }
precompile-utils = { path = '../../precompiles/utils', default-features = false }
runtime-common = { path = '../common', default-features = false }


[features]
default = ["std", "aura"]
aura = []
runtime-benchmarks = [
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'hex-literal',
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'pallet-multisig/runtime-benchmarks',
	'sp-runtime/runtime-benchmarks',
	'pallet-contracts/runtime-benchmarks',
	'parachain-staking/runtime-benchmarks',
	'pallet-block-reward/runtime-benchmarks',

	'pallet-ethereum/runtime-benchmarks',
	'pallet-collective/runtime-benchmarks',
	'pallet-xcm/runtime-benchmarks',
	'xcm-builder/runtime-benchmarks',
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",

	'peaq-pallet-transaction/runtime-benchmarks',
	'peaq-pallet-did/runtime-benchmarks',
	'peaq-pallet-rbac/runtime-benchmarks',
	'peaq-pallet-storage/runtime-benchmarks',
]

std = [
	'codec/std',
	'scale-info/std',
	'frame-executive/std',
	'frame-support/std',
	'frame-system-rpc-runtime-api/std',
	'frame-system/std',
	'pallet-aura/std',
	'pallet-balances/std',
	'pallet-randomness-collective-flip/std',
	'pallet-sudo/std',
	'pallet-timestamp/std',
	'pallet-transaction-payment-rpc-runtime-api/std',
	'pallet-transaction-payment/std',
	'pallet-multisig/std',
	'sp-api/std',
	'sp-block-builder/std',
	'sp-consensus-aura/std',
	'sp-core/std',
	'sp-inherents/std',
	'sp-offchain/std',
	'sp-runtime/std',
	'sp-session/std',
	'sp-std/std',
	'sp-transaction-pool/std',
	'sp-version/std',
	'sp-weights/std',
	'pallet-contracts/std',
	'pallet-contracts-primitives/std',
	'peaq-pallet-did/std',
	'peaq-pallet-did-runtime-api/std',
	'peaq-pallet-transaction/std',
	'peaq-pallet-rbac/std',
	'peaq-pallet-rbac-runtime-api/std',
	'peaq-pallet-storage/std',
	'peaq-pallet-storage-runtime-api/std',
	'pallet-utility/std',
	'pallet-treasury/std',
	'pallet-collective/std',
	'pallet-vesting/std',

	# ETH support
	'sp-io/std',
	'fp-evm/std',
	'fp-self-contained/std',
	'pallet-base-fee/std',
	'pallet-dynamic-fee/std',
	'pallet-ethereum/std',
	'pallet-evm/std',
	'pallet-evm-precompile-simple/std',
	'pallet-evm-precompile-modexp/std',
	'pallet-evm-precompile-sha3fips/std',
	'sp-std/std',
	'fp-rpc/std',

	# Tracing
	'evm-tracing-events/std',
	'peaq-evm-tracer/std',
	'peaq-rpc-primitives-debug/std',
	'peaq-rpc-primitives-txpool/std',

	# Parachain
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"cumulus-primitives-timestamp/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-aura-ext/std",
	"parachain-info/std",

    "polkadot-parachain/std",
    "polkadot-primitives/std",
    "polkadot-runtime-common/std",

	# Customized Parachain
    "pallet-session/std",
    "pallet-authorship/std",

    "parachain-staking/std",
    "pallet-block-reward/std",

	# XCM
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"orml-currencies/std",
	"orml-tokens/std",
	"orml-traits/std",
	"orml-xtokens/std",

	# Customized
	"peaq-primitives-xcm/std",
	"precompile-utils/std",
	"runtime-common/std",
]

# Must be enabled for tracing runtimes only
evm-tracing = [
	'evm-tracing-events',
	'peaq-evm-tracer',
	'rlp',
	'sha3'
]
