[package]
name = "peaq-rpc-trace"
license = "GPL-3.0-only"
version = "0.6.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
ethereum = { workspace = true, default-features = true, features = [ "with-codec" ] }
ethereum-types = { workspace = true, default-features = true }
fc-consensus = { workspace = true, default-features = true }
fc-rpc = { workspace = true, default-features = true, features = [ "rpc-binary-search-estimate" ] }
fc-rpc-core = { workspace = true, default-features = true }
fc-storage = { workspace = true, default-features = true }
fp-rpc = { workspace = true, default-features = true }
futures = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }
peaq-client-evm-tracing = { workspace = true }
peaq-rpc-core-trace = { workspace = true }
peaq-rpc-core-types = { workspace = true }
peaq-rpc-primitives-debug = { workspace = true }
sc-client-api = { workspace = true, default-features = true }
sc-network = { workspace = true, default-features = true }
sc-utils = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = [ "derive" ] }
sha3 = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-std = { workspace = true, default-features = true }
sp-transaction-pool = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true, features = [ "sync", "time" ] }
tracing = { workspace = true, default-features = true }
