name: Rust

on:
  push:
    branches: [ main ]
  release:
    types:
      - published

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile node
      uses: addnab/docker-run-action@v2
      with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        image: ghcr.io/peaqnetwork/peaq-node-builder:latest
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work

          echo "Building tracing enabled wasm"
          cargo build --release -p peaq-node-runtime --features "std aura evm-tracing on-chain-release-build"

          echo "Building network node"
          cargo build --release --features on-chain-release-build

    - uses: tenhaus/get-release-or-tag@v2
      id: tag

    - name: Compress peaq node
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ./target/release/
        files: |
          ./peaq-node
        outPath: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz

    - name: Compress tracing enabled wasm runtime
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ./target/release/wbuild/peaq-node-runtime/
        files: |
          ./peaq_node_runtime.wasm
        outPath: peaq-node-runtime-with-tracing-${{ steps.tag.outputs.tag }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
          peaq-node-runtime-with-tracing-${{ steps.tag.outputs.tag }}.tar.gz

#     - name: Upload peaq-node
#       uses: actions/upload-artifact@v3
#       with:
#         name: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
#         path: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz

#     - name: Upload peaq-node-runtime-with-tracing
#       uses: actions/upload-artifact@v3
#       with:
#         name: peaq-node-runtime-with-tracing-${{ steps.tag.outputs.tag }}.tar.gz
#         path: peaq-node-runtime-with-tracing-${{ steps.tag.outputs.tag }}.tar.gz
