name: Rust

on:
  push:
    branches: [ main ]
  release:
    types:
      - published
      
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Compile non tracing node
      uses: addnab/docker-run-action@v2
      with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        image: ghcr.io/peaqnetwork/peaq-node-builder:latest
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work
          cargo build --release

    - uses: tenhaus/get-release-or-tag@v2
      id: tag
        
    - name: Compress action step
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./target/release
        files: |
          ./peaq-node
        outPath: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
        

    - uses: actions/upload-artifact@v3
      with:
        name: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
        path: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
