name: Trigger Manually Build and Deploy

on:
  push:
    branches:
      - ci/1206449610772777_auto-deployment-fix

jobs:
  trigger-build_and_publish:
    name: Build and Publish Docker image
    runs-on: ubuntu-20.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Trigger Build Docker Image workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: ./.github/workflows/publishondhr.yml
        repo:  ${{ github.repository_owner }}/${{ github.event.repository.name }}
        token: ${{ secrets.GHACTION }}
  trigger-deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: trigger-build_and_publish
    steps:
    - name: Trigger Deployment workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: ./.github/workflows/trigger-deployment.yml
        repo:  ${{ github.repository_owner }}/${{ github.event.repository.name }}
        token: ${{ secrets.GHACTION }}
  trigger-autotest:
    name: Autotest
    runs-on: ubuntu-20.04
    needs: trigger-deploy
    steps:
    - name: Trigger Autotest workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        github_token: ${{ secrets.GHACTION }}
        workflow_file_name: trigger-autotest.yml
        ref: dev
        trigger_workflow: true
        wait_workflow: true
  

  
