name: Build and Publish
on:
  push:
    branches:
      - 'ci/1205782676034164_auto-deploy'
    tags:
      - 'peaq-dev-v*' # For the peaq-dev's env in the parchain-launch usage
      - 'krest-v*' # For the krest env in the parchain-launch usage
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: "Free Disk Space (insightsengineering/disk-space-reclaimer)"
        uses: insightsengineering/disk-space-reclaimer@v1.1.0

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_REG_PARACHAIN}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: scripts/Dockerfile
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: Extract Tag
        id: image-version
        run: |
          input_string=${{ steps.meta.outputs.tags}}
          tag=$(echo "$input_string" | cut -d ':' -f 2)
          echo "Extracted Tag: $tag"
          echo "tag=$(echo "$input_string" | cut -d ':' -f 2)" 
          echo "::set-output name=tag::$tag"
          echo "tag=$(echo "$input_string" | cut -d ':' -f 2)" >> $GITHUB_ENV
          echo ${{ env.tag }}
          #echo "::set-env name=tag::$tag"
          echo ${{ steps.image-version.outputs.tag }}
      
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: push_to_registry
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AUTOTEST_HOST }}
          username: ${{ secrets.AUTOTEST_USERNAME }}
          key: ${{ secrets.SSH_KEY_AUTOTEST }}
          port: ${{ secrets.AUTOTEST_SSH_PORT }}
          script: |
            cd /home/jay/parachain-launch/yoyo/
            echo ${{ env.tag }}
            echo ${{ steps.image-version.outputs.tag }}
            sudo TAG=${{ env.tag }} docker compose pull
            sudo TAG=${{ env.tag }} docker compose down -v
            sudo TAG=${{ env.tag }} docker compose up -d --build --remove-orphans
